### PR TITLE
Prepare for Play 2.9

### PR DESCRIPTION
**Pull request by mkurz**
Do not merge yet, WIP

Depends on the next Play milestone release which hopefully brings Scala 3 artifacts.

### CODE REVIEW

**Comment by mkurz** [comment]
@jamesward If you want I can also set up GitHub actions, migrating away from travis, including release by tag, so you can just push a tag to trigger a new release. What do you think?

Also would you mind if I add this repo to https://github.com/VirtusLab/scala-steward-repos/blob/main/repos-github.md so it gets visited by scala-steward for easier and up-to-date depency updates?

**Comment by jamesward** [comment]
I'd love both those improvements :)  I've invited you as repo admin.  Feel free to make whatever changes you see fit.  Thank you!

**Comment by mkurz** [comment]
Even better, thanks! I will come back to this PR asap. Thanks!

**Comment by mkurz** [comment]
@jamesward Can you give me access to 
* https://github.com/webjars/sample-play2
* https://github.com/webjars/sample-play2-requirejs

as well? I will updated them when I find them. Thanks!

**Comment by mkurz** [comment]
Hmm. maybe also
* https://github.com/webjars/webjars-file-service

it's also Play app. Thanks!

**Comment by mkurz** [comment]
@jamesward I need your help. I want to switch to sbt-ci-release, can you please take a look at https://github.com/sbt/sbt-ci-release/#secrets and add following repository secrets to this repo (via this page https://github.com/webjars/webjars-play/settings/secrets/actions):
* `PGP_PASSPHRASE`
* `PGP_SECRET`
* `SONATYPE_PASSWORD`
* `SONATYPE_USERNAME`

You could even add them as organization secrets so they are available not only for this repo but for all within the webjars organization: https://github.com/organizations/webjars/settings/secrets/actions (I can not access this page but I know the url ;)

This way when using sbt-ci-release I will be able to publish releases when creating a tag and even snapshots for each commit to the master branch.

If you don't want to add you sonatype username/password, you can instead generated a user token: Login to https://oss.sonatype.org/, then on the top right click on your username, click on Profile, then in the "Summary" drop down choose "User token" and then button "Access user token". This gives you a username/password that can be used as alternative.

Would be helpfull thanks!

**Comment by jamesward** [comment]
I've added those organizational secrets.  Thanks for the easy instruction!

**Comment by mkurz** [comment]
I created a 2.9.x branch to which I am going this merge this PR against now, so I am not touching the stable master branch until 2.9.x is ready. When Play 2.9 final arrives I will fast forward merge master to 2.9.x and probably remove 2.9.x.

**Comment by mkurz** [comment]
@jamesward Done. The 2.9.x branch has GitHub actions workflows for testing and publishing set up now: https://github.com/webjars/webjars-play/actions
For a release you now need to git tag and push that tag, done, see README in https://github.com/webjars/webjars-play/tree/2.9.x

Just released 2.9.0-M1 and then  2.9.0-M3 (to stay on par with the Play versions). 2.9.0-M1 already up on maven central: https://repo1.maven.org/maven2/org/webjars/webjars-play_2.13/2.9.0-M1/ and https://repo1.maven.org/maven2/org/webjars/webjars-play_3/2.9.0-M1/

**Comment by jamesward** [comment]
Amazing! Thank you!

**Pull request merged**
