### PR TITLE
Use Play 2.8.0-RC2

### PR DESCRIPTION
**Pull request by marcospereira**
Hey @jamesward, can we have a release for this RC?

Thanks!

### CODE REVIEW

**Comment by jamesward** [comment]
For some reason I'm getting some local test failures.  I need to investigate.

**Comment by marcospereira** [comment]
Sure, let me know if I can help somehow.

**Comment by jamesward** [comment]
For some reason manually removing my `project/project`, `project/target`, and `target` dirs made it work.

**Comment by marcospereira** [comment]
> For some reason manually removing my `project/project`, `project/target`, and `target` dirs made it work.

Oh, okay. That happened to me before. I appreciate if you can let me know about a release so that I can test it in our sample applications.

Again, thank you @jamesward.

**Comment by jamesward** [comment]
The release should be on its way to maven central.

**Pull request merged**
