### PR TITLE
Use AdoptOpenJDK 8 & 11 in Travis build

### PR DESCRIPTION
**Pull request by marcospereira**
@jamesward not sure how the branch policy works here, but you may want to backport this to the current stable branch if it exists (I mean, the branch supporting Play 2.7). As usual, let me know if I can help somehow.

### CODE REVIEW

**Comment by jamesward** [comment]
Thanks!  Seems like we have some work to do to support JDK 11.

**Comment by dwijnand** [comment]
Opened https://github.com/webjars/webjars-locator/issues/2, before seeing the https://github.com/webjars/webjars-locator-core/pull/34 backlink to here.

**Comment by jamesward** [comment]
webjars-play 2.8.0-RC1 has been released.  Let me know if you have any issues.  Thanks!

**Comment by jamesward** [comment]
Oh, looks like it is still failing on JDK 11 :(  I need to investigate further.

**Comment by jamesward** [comment]
This seems to be because we ignore the parent classloaders in webjars-locator-core.  I'm not sure why I did that.  Gonna make a change down there and roll it up.

**Comment by jamesward** [comment]
Ok, `2.8.0-RC1-1` has been released which should work on Java 11.

**Pull request merged**
