### PR TITLE
update to play 2.4 and new libs

### PR DESCRIPTION
**Pull request by vmouta**

### CODE REVIEW

**Comment by jamesward** [comment]
Whoops. Just remembered that there is already a branch for the 2.4 stuff. I'm going to bump to M3 there and release it.

**Comment by jamesward** [comment]
Looks like the 2.4.0-M3 artifacts for Scala 2.10 don't exist.  I'm investigating.

**Comment by jamesward** [comment]
Ok, `2.4.0-M3` has been released. Can you try it?

**Comment by vmouta** [comment]
Sorry for taking so long, I did test it and works fine for me, however I'm very new at so it may happen I forgot to have a look at something...

**Pull request merged**
